### ISSUE TITLE
Error when accessing http://localhost:34115

### ISSUE THREAD

**Issue by OneSeven** [codydbentley/wails-vite-vue-the-works#1]
```
Uncaught SyntaxError: Unexpected token '{'
```

My judgment seems to be the lack of some files to load. Is it a problem with vue? Or is it a problem with wails?

**Comment by sircodemane** [comment]
@OneSeven I would need to see more of the error message and know more about where it's coming from to diagnose the issue. Can you paste more of the error please?

**Comment by OneSeven** [comment]
> @OneSeven I would need to see more of the error message and know more about where it's coming from to diagnose the issue. Can you paste more of the error please?

Wails did not report any errors, and the web only threw this error.
Without any changes
I ran npm run dev first
Then run wails dev,
Is it operating normally on your side?

wails version : v2.0.0-beta.15

**Comment by sircodemane** [comment]
~~@OneSeven I have installed wails v2.0.0-beta.15 and tested a fresh project with this template. I ran `npm i && npm run dev` in the `frontend` folder, and I ran `wails dev` in the project folder. It is working as expected.~~

~~To determine an issue, I will need to know more information. Please send me:
Node environment info: `node -v` and `npm -v`
Also, reproduce the error and copy paste the entire error log, `Uncaught SyntaxError: Unexpected token '{'` only tells me part of went wrong and I need the rest of the error message to help determine a cause.~~

This test worked in the wails window, however I did find the same issue when launching a chrome browser and navigating to `localhost:34115`. I believe this is an issue caused by Wails, however I will do some testing to be sure.
